# Inspired by this issue: https://github.com/junegunn/vim-plug/issues/730
- name: Install vim plugins
  listen: "install vim plugins"
  shell: |
    vim -es -u "$HOME/.vimrc" -i NONE -c 'PlugInstall --sync' -c 'qa'
