---
- name: Ensure vim autoload folder exists
  file:
    path: "{{ ansible_env['HOME'] }}/.vim/autoload"
    state: directory

- name: Install vimplug
  get_url:
    dest: "{{ ansible_env['HOME'] }}/.vim/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

